server:
  port: 8898

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/prod_course_db
    username: andres
    password: Campeon1!
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
